---
title: "HelpResponse"
author: "Craig Alder"
date: "4/3/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rvest)
library(stringr)
```

```{r}

lapply(monthurls, FUN=function(URLLink){
monthscrap <- read_html(URLLink)

monthurls2 <- monthscrap %>%
  html_nodes(".text a") %>%
  html_attr("href") %>%
  html_text() %>%
  as.character()
  monthurls2 <-ifelse(length(nchar(monthurls2)) !=0 , monthurls2, 0)

Checker = data.frame(monthurls2)

})

    amalah_arch1 <- read_html("http://www.amalah.com/amalah/archives.html")
       monthurls <- amalah_arch1 %>%
       html_nodes(".archive-date-based a") %>%
       html_attr("href")
    links <- amalah_arch1 %>%
       html_node(".archive-date-based a") %>%
       html_text()

get_month_urls <- function(url, css_or_xpath="*"){
  html_attr("href")
    html_nodes(".archive-date-based a")
      html("http://www.amalah.com/amalah/2017/04/index.html")
}
lapply(monthurls, get_month_urls, css_or_xpath="a[class=message]")
```

```{r}
  url_list    <- c(monthurls)

  get_html_text <- function(url, css_or_xpath="*"){
      html_text()
        html_attr("href")
         html_nodes(".text a")
           read_html("http://www.ashleyannphotography.com/blog/2017/04/",url) 
   }

lapply(url_list, get_html_text)
#Sys.sleep(runif(n = 1, min = 1,  max = 3))




```

```{r}
dfList <- lapply(monthurls, function(i) {
    webpage <- read_html(i)
    draft_table <- html_nodes(webpage, '.text a')
    draft <- html_attr('href')[[1]]
    html_text()
})

finaldf <- do.call(rbind, dfList) 


```

```{r}

read_page <- function(name) {
    message(name)
    read_html(cran_link("Archive", name)) %>% 
        html_nodes("td") %>% 
        html_text()
}

archives_scraped <- archives_processed %>%
    mutate(page = map(Name, read_page))
```
